# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-14 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('text', models.TextField(verbose_name='\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442')),
                ('start', models.DateField(default=datetime.date(2017, 5, 14), verbose_name='\u0414\u0430\u0442\u0430 \u041d\u0430\u0447\u0430\u043b\u0430')),
                ('finish', models.DateField(blank=True, verbose_name='\u0414\u0430\u0442\u0430 \u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u044f',
                'verbose_name_plural': '\u041a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0424\u0418\u041e')),
                ('position', models.CharField(max_length=100, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('image', models.ImageField(upload_to='personals/images', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Event', verbose_name='\u0412 \u043a\u0430\u043a\u043e\u0439 \u043a\u043e\u043d\u0444\u0435\u0440\u0435\u043d\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0421\u043f\u0438\u043a\u0435\u0440',
                'verbose_name_plural': '\u0421\u043f\u0438\u043a\u0435\u0440\u044b',
            },
        ),
    ]
