# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-15 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='conference/images', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(default=datetime.date(2017, 5, 15), verbose_name='\u0414\u0430\u0442\u0430 \u041d\u0430\u0447\u0430\u043b\u0430'),
        ),
    ]
